datadog:
site: us5.datadoghq.com

agent:
majorVersion: 7
version: "7.66.0"

tags:
environment: demo
project: markehler-datadog
owner: mark

features:
clusterChecks: true
orchestratorExplorer: true
logsEnabled: true
processMonitoring: true

aks:
clusterName: MarkEhler-demo-aks

vm:
installMethod: script
