name: Terraform Azure Setup
description: Logs into Azure, sets ARM vars, installs Terraform, and runs init/fmt/validate

inputs:
  environment:
    required: true
    description: Name of the environment
  AZURE_CREDENTIALS:
    required: true
    description: Azure service principal credentials (JSON string)
  deployer_app_id:
    description: 'GitHub App ID'
    required: true
  deployer_app_private_key:
    description: 'GitHub App private key'
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse AZURE_CREDENTIALS and export ARM variables
      shell: bash
      run: |
        echo '${{ inputs.AZURE_CREDENTIALS }}' > creds.json
        echo "ARM_CLIENT_ID=$(jq -r .clientId creds.json)" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret creds.json)" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=$(jq -r .tenantId creds.json)" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId creds.json)" >> $GITHUB_ENV

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: Set up kubelogin
      uses: azure/use-kubelogin@v1.2
      with:
        kubelogin-version: 'v0.0.24'
      
    - name: Generate GitHub Application token
      id: app-token
      uses: peter-murray/workflow-application-token-action@v4
      with:
        application_id: ${{ inputs.DEPLOYER_APP_ID }}
        application_private_key: ${{ inputs.DEPLOYER_APP_PRIVATE_KEY }}
        organization: DisasterTechInc

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      shell: bash
      env:
        GIT_ASKPASS: /bin/echo
        GIT_USERNAME: x-access-token
        GIT_PASSWORD: ${{ steps.app-token.outputs.token }}
      run: |
          git config --global credential.helper store
          git config --global url."https://x-access-token:${GIT_PASSWORD}@github.com/".insteadOf "https://github.com/"
          terraform init -backend-config="key=${{ inputs.environment }}.terraform.tfstate"

    - name: Terraform Format Check
      shell: bash
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      shell: bash
      run: terraform validate