name: Deploy Infrastructure

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: Target environment
        options:
          - dev
          - qa
          - production
          - test

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Application token
        id: app-token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.DEPLOYER_APP_ID }}
          application_private_key: ${{ secrets.DEPLOYER_APP_PRIVATE_KEY }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        shell: bash
        env:
          GIT_ASKPASS: /bin/echo
          GIT_USERNAME: x-access-token
          GIT_PASSWORD: ${{ steps.app-token.outputs.token }}
        run: |
            git config --global credential.helper store
            git config --global url."https://x-access-token:${GIT_PASSWORD}@github.com/".insteadOf "https://github.com/"
            terraform init

      - name: Terraform Format Check
        shell: bash
        run: terraform fmt -recursive

      - name: Terraform Validate
        shell: bash
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform plan -input=false -out=tfplan
          terraform show -no-color tfplan > tfplan.txt
          sed -E 's/^(\s*)\+/\1🟢 **Add**/; s/^(\s*)\~/\1🟡 **Change**/; s/^(\s*)\-/\1🔴 **Remove**/' tfplan.txt > plan.md
      