name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        description: Target environment to destroy
        options:
          - dev
          - qa
          - production
          - test

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Application token
        id: app-token
        uses: peter-murray/workflow-application-token-action@v4
        with:
          application_id: ${{ secrets.DEPLOYER_APP_ID }}
          application_private_key: ${{ secrets.DEPLOYER_APP_PRIVATE_KEY }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Generate SSH key pair
        shell: bash
        run: |
          mkdir -p "$RUNNER_TEMP"
          ssh-keygen -t rsa -b 4096 -f "$RUNNER_TEMP/terraform_ssh_key" -N "" -q
          echo "TF_VAR_ssh_public_key<<EOF" >> $GITHUB_ENV
          cat "$RUNNER_TEMP/terraform_ssh_key.pub" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Terraform Init
        shell: bash
        working-directory: application/terraform
        env:
          GIT_ASKPASS: /bin/echo
          GIT_USERNAME: x-access-token
          GIT_PASSWORD: ${{ steps.app-token.outputs.token }}
        run: |
            git config --global credential.helper store
            git config --global url."https://x-access-token:${GIT_PASSWORD}@github.com/".insteadOf "https://github.com/"
            terraform init

      - name: Terraform Destroy
        working-directory: application/terraform
        run: terraform destroy -auto-approve
